theme: jekyll-theme-minimal
title: Amy's Page
description: Pianist, editor, and Nick's gf
info: |
  Find me on [IMSLP](https://imslp.org/wiki/User:AmyChang)

  Email me at amychang134@gmail.com
logo: photomejpg.jpg
