theme: jekyll-theme-minimal
title: Amy's Page
description: Pianist, editor and enthusiastic foodie
info: |
  Find me on [IMSLP](https://imslp.org/wiki/User:AmyChang)

  Email me [here](mailto:amychang134@gmail.com)
logo: photomejpg.jpg
